{{- if and .Values.registryKey.enabled (not .Values.imagePullSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-dynamic-infrastructure.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.registryKey.registry }}": {
          "username": "{{ .Values.registryKey.username }}",
          "password": "{{ .Values.registryKey.password }}"
        }
      }
    }
{{- end }}
