apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "nlweb-dynamic-infrastructure-user.serviceAccountName" . }}
type: kubernetes.io/service-account-token
