apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-dynamic-infrastructure.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{/* Attach imagePullSecrets if provided */}}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . | quote }}
{{- end }}
{{- end }}
