apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nlweb-dynamic-infrastructure-user.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . | quote }}
{{- end }}
{{- end }}
